spring.application.name=stray-care-system

# Database Connection
spring.datasource.url=jdbc:mysql://localhost:3306/stray_care_system
spring.datasource.username=root
spring.datasource.password=straycare123
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

# App Port
server.port=8080